server:
  port: 8080
  shutdown: graceful
  servlet:
    encoding:
      charset: UTF-8
      enabled: true
      force: true


spring:
  data:
    mongodb:
      uri: mongodb://localhost:27017/db_web_streaming